81 notitie frontend model logic t4
ZuydUniversity/B2C6_B2C_Frontend pull request #85
Opened 2024-06-07 09:30 UTC by Megalomizer

Added basics of all class models to the frontend with a unit test for the frontend to test the model itself.

2024-06-07 11:58 UTC, Toffeegaming requested changes
Over algemeen goed, alleen op enkele plaatsen verwarrend taalgebruik of spelfouten, graag hier naar kijken.

2024-06-07 11:58 UTC, Toffeegaming commented on src/abstracts/Dictionairy.ts
Dit kan veranderd worden naar dictionary

2024-06-07 11:58 UTC, Toffeegaming commented on src/models/Appointment.tsx
Gaat een appointment over meerdere dagen of heeft het alleen een begin en eindtijd?
Zoals het er nu staat lijkt het alsof het altijd meerdere dagen of een hele dag duurt.
Dus de naam zou naar starttime en endtime gewijzigd kunnen worden.

2024-06-07 11:58 UTC, Toffeegaming commented on src/models/DoctorSession.tsx
> +    startdate: Date,
Hetzelfde als bij de appointment, het lijkt nu 1 of meerdere dagen te duren.

2024-06-07 11:58 UTC, Toffeegaming commented on src/models/Medication.tsx
> +  Patients!: Array<Patient>;
Willen we bijhouden in de medicatie welke patiënten ze gebruiken?
Andere manier is per patient bijhouden welke medicatie ze gebruiken.

2024-06-07 11:58 UTC, Toffeegaming commented on src/models/MyometrySession.tsx
> +    startdate: Date,
Ditto van de appointment.

2024-06-07 11:58 UTC, Toffeegaming commented on src/models/Patient.tsx
> +  Gender!: boolean; // True = Male | False = Female
Ik zou dit niet doen, ik zou dit ofwel veranderen naar sex, dus biologisch geslacht, of als het gender blijft heten dit veranderen naar 0 man, 1 vrouw, 3 overig

2024-06-07 11:58 UTC, Toffeegaming commented on src/models/Patient.tsx
> +  Medications!: Array<Medication>;
Ik zie dat per patient de medicatie wordt bijgehouden, dus die array van patienten in de medicatie lijkt mij overbodig, anders krijg je beetje een kringverwijzing naar elkaar.

2024-06-07 11:58 UTC, Toffeegaming commented on src/models/RadiologySession.tsx
> +    startdate: Date,
Ditto appointment

2024-06-07 11:58 UTC, Toffeegaming commented on src/models/Session.tsx
> +  Startdate!: Date;
Ditto appointments

2024-06-07 12:03 UTC, Megalomizer commented
Tristan, zou jij kunnen kijken naar bovenstaande feedback?? Dit zijn grotendeels aanpassingen aan het klasse diagram

2024-06-07 15:39 UTC, Megalomizer commented on src/models/Appointment.tsx
Aangezien de datum van de appointment ook nodig is heb ik het momenteel aangepast naar **datetime**, indien tijd belangrijker is kunnen we het aanpassen naar **time** en een nieuwe property hebben met alleen de dag

2024-06-07 18:56 UTC, Megalomizer reviewed
Changes have been reviewed!

2024-06-10 07:26 UTC, Mineplay5780 approved these changes

2024-06-10 07:27 UTC, Toffeegaming approved these changes
Goeie

2024-06-10 07:50 UTC, merged